# -*- coding: utf-8 -*-
"""nlp-t5-text-summarization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19e2LoIc7AplYNjCM2jzLrZ8pldK5Ubd3
"""

!pip install transformers sentencepiece torch

from transformers import T5Tokenizer, T5ForConditionalGeneration

model_name = "t5-small"

tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

print("T5 Model Loaded Successfully!")

text = """
Natural Language Processing is a branch of Artificial Intelligence that enables
computers to understand, interpret, and generate human language. NLP is widely
used in applications such as chatbots, machine translation, sentiment analysis,
text summarization, question answering, and speech recognition. Modern NLP
systems rely heavily on Transformer-based architectures to achieve state-of-the-art
performance across various tasks.
"""

input_text = "summarize: " + text

inputs = tokenizer.encode(
    input_text,
    return_tensors="pt",
    max_length=512,
    truncation=True
)

summary_ids = model.generate(
    inputs,
    max_length=50,
    min_length=20,
    length_penalty=2.0,
    num_beams=4,
    early_stopping=True
)

summary = tokenizer.decode(
    summary_ids[0],
    skip_special_tokens=True
)

print("Original Text:\n")
print(text)

print("\nSummary:\n")
print(summary)

paragraph = input("Enter a paragraph:\n")

inputs = tokenizer.encode(
    "summarize: " + paragraph,
    return_tensors="pt",
    max_length=512,
    truncation=True
)

summary_ids = model.generate(
    inputs,
    max_length=50,
    min_length=20,
    num_beams=4,
    early_stopping=True
)

summary = tokenizer.decode(
    summary_ids[0],
    skip_special_tokens=True)

print("\nSummary:\n")
print(summary)

original_words = len(text.split())
summary_words = len(summary.split())

print("Original Words:", original_words)
print("Summary Words :", summary_words)